### ISSUE TITLE
Textured Object sample not working without post processing

### ISSUE THREAD

**Issue by rawnsley** [google/filament#651]
**Describe the bug**
The Android Textured Object sample renders incorrectly when post-processing is disabled.

**To Reproduce**
1. Uncomment the line in the sample code [that sets isPostProcessingEnabled to false](https://github.com/google/filament/blob/master/android/samples/textured-object/app/src/main/java/com/google/android/filament/textured/MainActivity.kt#L125)
2. Run the sample on an Android device

**Expected behavior**
Both the skybox and the object should be visible at least.

**Screenshots**

This is the default behaviour:

![default](https://user-images.githubusercontent.com/303516/50165747-75ddaa00-02dd-11e9-8022-13c73c98fd54.png)

When post-processing is disabled, the skybox is visible, but there's no object:

![nopost](https://user-images.githubusercontent.com/303516/50165762-7ece7b80-02dd-11e9-9cde-eff9743407a2.png)

If the skybox is disabled the object appears, but there's some sort of depth buffer problem. The scene light was turned up by a factor of 10 for this screenshot:

![nopost-noskybox](https://user-images.githubusercontent.com/303516/50165778-85f58980-02dd-11e9-9625-7a605cb70d79.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 1
 - OS: Android Pie 9.0

**Comment by romainguy** [comment]
I bet it's because we have a bug that causes to not allocate a depth buffer in the surface's render target when post-processing is disabled.

**Comment by romainguy** [comment]
A workaround is to enabled dynamic resolution btw.

**Comment by rawnsley** [comment]
I'm no longer sure it is a depth buffer issue. GAPID says that a depth buffer was allocated and I get the same problem with the lit-cube demo, which is a convex shape and should never render faces you can't see, but actually what you get is this:

![screen](https://user-images.githubusercontent.com/303516/51248882-6c516b80-1989-11e9-9b03-451dc6387d0d.png)

It appears that the visible faces are rendering with color as expected, but the bottom face is also being rendered in black and appearing on top of the other faces.

When I check the OpenGL commands in GAPID there is nothing suspicious and it renders fine in the preview (albeit using my computer's GPU because the rendering on the target device never works for me). It renders the cube primitives once and the GPU state seems to be correct just before the call to glDrawArrays:

<img width="268" alt="screenshot 2019-01-16 at 12 33 00" src="https://user-images.githubusercontent.com/303516/51249346-e7675180-198a-11e9-82fc-dbcae9ff8573.png">

That bottom face should have culled and should never have made it to the fragment shader.

FYI: if I change the material to be "unlit" the artefact goes away.

**Comment by rawnsley** [comment]
It almost certainly IS a depth buffer issue because if I add...

`            EGL_DEPTH_SIZE, 16,
`

...to the required [EGL config attributes](https://github.com/google/filament/blob/master/filament/src/driver/opengl/PlatformEGL.cpp#L183) it works.

I can't see why it doesn't happen all the time though, which makes me nervous that I haven't nailed it completely. Perhaps some difference in the state of the other parameters passed to eglChooseConfig that nudges it in the right direction?

It might also explain why the GAPID rendering on the desktop looks fine if the config it uses has a depth buffer by default.

Also, the winding order on the -Y face of the cube in the lit-cube demo is wrong, but I don't think it's worth raising an explicit issue about.

Apologies for the red herring earlier and I hope this info is of more use.

**Comment by romainguy** [comment]
It does look like the winding of one of the cube faces is wrong indeed. I'll fix it as well. We're currently writing a frame graph API which should lead to fixing this issue but it'll take a while.

**Comment by romainguy** [comment]
@pixelflinger the frame graph doesn’t reallocate the egl surface yet right?

**Comment by pixelflinger** [comment]
This should be fixed now.

**Comment by daniilsunyaev** [comment]
I think I still issuing it for webgl. Not sure if this is the same issue.
Whenewer I try to add `this.view.setPostProcessingEnabled(true);` [here](https://github.com/google/filament/blob/master/docs/webgl/tutorial_suzanne.js#L61), and launch `demo_suzanne.html`, the model dissapears.
![filament_post_processing_enabled](https://user-images.githubusercontent.com/3955599/59011532-b609f800-883d-11e9-969d-2b9d3550622b.jpg)
![filament_post_processing_disabled](https://user-images.githubusercontent.com/3955599/59011531-b609f800-883d-11e9-808e-15f185f7c797.jpg)

**Comment by prideout** [comment]
Thanks @daniilsunyaev, indeed this appears to still be an issue, at least on WebGL.  We'll look into it.

**Comment by prideout** [comment]
Actually @daniilsunyaev this is not a bug, you simply need to enable the depth buffer.  Change the following line:

```js
const engine = this.engine = Filament.Engine.create(this.canvas);
```

to:

```js
const engine = this.engine = Filament.Engine.create(this.canvas, {depth: true});
```

**Comment by rawnsley** [comment]
> Actually @daniilsunyaev this is not a bug, you simply need to enable the depth buffer. Change the following line:
> 
> ```js
> const engine = this.engine = Filament.Engine.create(this.canvas);
> ```
> 
> to:
> 
> ```js
> const engine = this.engine = Filament.Engine.create(this.canvas, {depth: true});
> ```

@prideout Is there an equivalent to this from the Java side? I'm still not getting a depth buffer by default when I turn off post-processing in the textured-object sample.

**Comment by prideout** [comment]
Hm, for now I think you would need to hack the `configAttribs` list in PlatformEGL.cpp by adding `EGL_DEPTH_SIZE, 16`. Typically we expect post-processing to be enabled and its individual features (tone mapping, FXAA, etc) to be toggled as needed.

@romainguy and @pixelflinger, let us know if you have thoughts wrt configurability of the backbuffer on Android.

**Comment by romainguy** [comment]
The frame graph should take care of this. This is an old bug, it might work now.
